[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
resonance_genesis = "EMrGu6bcLn7YjuTsf7YEQb5fecu4vukPFtU48v2y53k1"

[programs.localnet]
resonance_genesis = "EMrGu6bcLn7YjuTsf7YEQb5fecu4vukPFtU48v2y53k1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
