[features]
seeds = true
skip-lint = false

[programs.localnet]
resonance_genesis = "ReSo111111111111111111111111111111111111111"

[programs.devnet]
resonance_genesis = "ReSo111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
